name: doc
on:
  push:  # ToDo: Change to 'pull_request' after the workflow is established

jobs:
  doc:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
      - name: Install dependencies
        run: python -m pip install tox
      - name: Build documentation
        run: tox -e docs
      - name: Archive build results
        uses: actions/upload-artifact@v4
        with:
          name: ReadTheDocsDocumentation
          path: docs/build
