name: check
on:
  push:

jobs:
  doc:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3"
        run: python -m pip install tox
      - name: Build documentation
        run: tox -e docs
